version: "3.8"

services:
  tg-baidu:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/wangganghj/tg-baidu:latest
    container_name: tg-baidu
    restart: unless-stopped
    ports:
      - "8082:8082"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
      - WEB_HOST=0.0.0.0
      - WEB_PORT=8082
