version: "3.8"

services:
  tg-baidu:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/wangganghj/tg-baidu:latest
    container_name: tg-baidu
    restart: unless-stopped
    ports:
      - "8082:8082"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
    # network_mode: bridge
